### ISSUE TITLE
Problem Compiling

### ISSUE THREAD

**Issue by TomBoundless** [fehlfarbe/terraesp#4]
Sorry if this is not the correct place to post this, but I'm having issues around the DHT sensor.

In file included from src/sensors/dht_sensor.cpp:1:0:
src/sensors/dht_sensor.h:24:9: error: 'DHT' does not name a type
         DHT *sensor = nullptr;
         ^
src/sensors/dht_sensor.cpp: In constructor 'DHT11Sensor::DHT11Sensor(String, uint8_t, uint8_t)':
src/sensors/dht_sensor.cpp:7:5: error: 'sensor' was not declared in this scope
     sensor = new DHT(pin, type);
     ^
src/sensors/dht_sensor.cpp:7:18: error: expected type-specifier before 'DHT'
     sensor = new DHT(pin, type);
                  ^
src/sensors/dht_sensor.cpp: In member function 'bool DHT11Sensor::updateValues()':
src/sensors/dht_sensor.cpp:34:21: error: 'sensor' was not declared in this scope
     m_temperature = sensor->readTemperature();
                     ^
src/sensors/dht_sensor.cpp:95:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
*** [.pio\build\usb\src\sensors\dht_sensor.cpp.o] Error 1

I can't seem to figure out what the problem is. Running on platformio in VS Code.

**Comment by fehlfarbe** [comment]
Does it work when you open a terminal in VSCode and install the libraries with `pio lib install`?

**Comment by TomBoundless** [comment]
It doesn't unfortunately. 

The annoying thing is I'm not even using the DHT sensor, planning on using an SHT

**Comment by fehlfarbe** [comment]
Quick fix: I removed the include of dht_sensor in terrasesp.cpp and created a new branch: https://github.com/fehlfarbe/terraesp/tree/no-dht can you try it?

**Comment by TomBoundless** [comment]
Thanks for your quick responses.

It's giving me the same error again.

**Comment by fehlfarbe** [comment]
Maybe I found the initial bug: are you using Windows? There is a different/old `dht.h` in the `src` directory. Maybe Windows includes the old `dht.h` in `src` directory instead of the Adafruit `DHT.h` because it's case-insensitive. I removed the old `dht.h` in my latest commit on master branch.

**Comment by TomBoundless** [comment]
I am using Windows.

That latest commit has solved the problem and it has now successfully compiled!

Thanks very much for your help, this will make a brilliant Christmas present for my girlfriend.

**Comment by fehlfarbe** [comment]
Perfect! :smiley: 
Just open a new issue if something else doesn't work.

**Comment by TomBoundless** [comment]
Thanks very much!
