### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by Eisbaeeer** [fehlfarbe/terraesp#6]
Platformio get an error by compiling the code.
![image](https://user-images.githubusercontent.com/4928271/177784703-ba034543-5cb7-4316-983a-4138b870ffb1.png)

src/Threshold.cpp:132:43: error: call of overloaded 'abs(long unsigned int)' is ambiguous

**Comment by LuigiPapparotti** [comment]
Cast the argument to **abs()** to **int** or another suitable type:

`if(is_active && abs(((int)millis()-activated))/1000.0 > duration){`
